Create terraform submodule for target account
solutionDrive/terraform-cross-account-role pull request #1
Opened 2018-03-02 11:43 UTC by solutionDrive-Alt

2018-03-05 14:30 UTC, michz approved these changes

2018-03-06 14:10 UTC, sd-lueckel requested changes

2018-03-06 14:10 UTC, sd-lueckel commented on README.md
> +data "aws_iam_policy_document" "s3_list_access" {
I suggest to use 's3_list_access_policy_document' as name instead of 's3_list_access'

2018-03-06 14:10 UTC, sd-lueckel commented on target_account/main.tf
> +data "aws_iam_policy_document" "cross_account_assume_role_policy" {
I suggest to use 'cross_account_assume_role_policy_document' as name

2018-03-06 14:43 UTC, sd-lueckel approved these changes

2018-03-06 15:13 UTC, merged